import extenddirectives from "./extend-directive";
import { Localchecked } from "./Localchecked";
import { Localref } from "./Localref";
import { Localhtml } from "./Localhtml";
import { Localtext } from "./Localtext";
import { Localvalue } from "./Localvalue";
import { Localcreated } from "./Localcreated";
import { Localupdated } from "./Localupdated";
import { Localunmounted } from "./Localunmounted";
import { Localmounted } from "./Localmounted";
extenddirectives("ref", Localref);
extenddirectives("html", Localhtml);
extenddirectives("text", Localtext);
extenddirectives("value", Localvalue);
extenddirectives("checked", Localchecked);
const Directives = extenddirectives;
Directives("mounted", Localmounted);
Directives("unmounted", Localunmounted);
Directives("updated", Localupdated);
Directives("created", Localcreated);
